//
// Generated file, do not edit! Created by opp_msgtool 6.1 from DataMsg.msg.
//

#ifndef __DATAMSG_M_H
#define __DATAMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DataMsg;
/**
 * Class generated from <tt>DataMsg.msg:16</tt> by opp_msgtool.
 * <pre>
 * packet DataMsg
 * {
 *     int truelen;
 *     int datalen;
 *     char data[8];
 *     char data2[8];
 * }
 * </pre>
 */
class DataMsg : public ::omnetpp::cPacket
{
  protected:
    int truelen = 0;
    int datalen = 0;
    char data[8] = {0};
    char data2[8] = {0};

  private:
    void copy(const DataMsg& other);

  protected:
    bool operator==(const DataMsg&) = delete;

  public:
    DataMsg(const char *name=nullptr, short kind=0);
    DataMsg(const DataMsg& other);
    virtual ~DataMsg();
    DataMsg& operator=(const DataMsg& other);
    virtual DataMsg *dup() const override {return new DataMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTruelen() const;
    virtual void setTruelen(int truelen);

    virtual int getDatalen() const;
    virtual void setDatalen(int datalen);

    virtual size_t getDataArraySize() const;
    virtual char getData(size_t k) const;
    virtual void setData(size_t k, char data);

    virtual size_t getData2ArraySize() const;
    virtual char getData2(size_t k) const;
    virtual void setData2(size_t k, char data2);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DataMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DataMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DataMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<DataMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DATAMSG_M_H

